### ISSUE TITLE
How to install fonts correctly

### ISSUE THREAD

**Issue by XiaoliChan** [hodcarrier/redheaddoc#1]
Env: Windows 11
Software: MiKTeX + CTex + WinEdt

When it compiling, it said can't find SimHei tfm file.
![image](https://user-images.githubusercontent.com/30458572/135025638-30bf4d0a-7733-4ea1-b8cf-85aff7755a21.png)

**Comment by hodcarrier** [comment]
hello，这个文档的编译器是 xetex，我刚刚用WINEDT尝试，需要把编译器设置为xetex。
另外，安装字体，我这边是把字体复制到这个目录：``C:\Windows\Fonts``
我这里准备了三种字体的方法，可以用
WIN自带，方正，和思源，你看实际情况使用。
